name: CI tests

on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          - ghc: '8.0'
            cabal: '2.4'
          - ghc: '8.2'
            cabal: '2.4'
          - ghc: '8.4'
            cabal: '2.4'
          - ghc: '8.6'
            cabal: '2.4'
          - ghc: '8.8'
            cabal: '3.0'
          - ghc: '8.10'
            cabal: '3.2'
          - ghc: '9.2'
            cabal: '3.4'
          - ghc: '9.4'
            cabal: 'latest'
          - ghc: '9.6'
            cabal: 'latest'
    steps:
    - uses: actions/checkout@v1
    - name: Install cabal/ghc
      run: |
        ghcup install ghc --set ${{ matrix.versions.ghc }}
        ghcup install cabal --set ${{ matrix.versions.cabal }}
    - name: Build and test
      run: |
          cabal update
          cabal test
